# TODO: Add Workflows

# When this repository is updated, it should trigger:
##   The execution of a subset of isanteplus tests for a standalone instance
##   Generation of a new, tagged docker-isanteplus-server image
##   Generation of a new, tagged docker-isanteplus-db image
##   New PR into sedish-haiti.org with automatically running CI

name: Maven Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8.0.232
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github-packages",
                "username": "${{ secrets.RELEASE_USERNAME }}",
                "password": "${{ secrets.RELEASE_TOKEN }}"
            }]
          githubServer: false
      - name: Build
        run: mvn -B package

